# Generated by Django 5.2.5 on 2025-09-05 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kasa Adı')),
                ('tip', models.CharField(choices=[('nakit', 'Nakit Kasası'), ('pos', 'POS Kredi Kartı'), ('kart', 'Harcama Kredi Kartı'), ('banka', 'Banka Hesabı'), ('other', 'Diğer')], max_length=20, verbose_name='Kasa Tipi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('baslangic_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Başlangıç Bakiyesi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Kasa',
                'verbose_name_plural': 'Kasalar',
                'ordering': ['tip', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='KasaCikis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('sebep', models.CharField(choices=[('kisisel', 'Kişisel Çekim'), ('harcama', 'Harcama'), ('odeme', 'Ödeme'), ('banka', 'Bankaya Yatırma'), ('diger', 'Diğer')], max_length=20, verbose_name='Çıkış Sebebi')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cikislar', to='kasa.kasa', verbose_name='Kasa')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kasa Çıkışı',
                'verbose_name_plural': 'Kasa Çıkışları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='KasaGiris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('sebep', models.CharField(choices=[('yatirim', 'Yatırım'), ('gelir', 'Gelir'), ('bankadan', 'Bankadan Çekim'), ('diger', 'Diğer')], max_length=20, verbose_name='Giriş Sebebi')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girisler', to='kasa.kasa', verbose_name='Kasa')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kasa Girişi',
                'verbose_name_plural': 'Kasa Girişleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='KasaHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('giris', 'Para Girişi'), ('cikis', 'Para Çıkışı')], max_length=10, verbose_name='Hareket Tipi')),
                ('kaynak', models.CharField(choices=[('satis', 'Satış'), ('gider', 'Gider'), ('virman', 'Virman'), ('cikis', 'Para Çıkışı'), ('giris', 'Para Girişi'), ('duzeltme', 'Düzeltme')], max_length=20, verbose_name='Kaynak')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('satis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satış ID')),
                ('gider_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gider ID')),
                ('virman_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Virman ID')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='kasa.kasa', verbose_name='Kasa')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kasa Hareketi',
                'verbose_name_plural': 'Kasa Hareketleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='KasaVirman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('hedef_kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelen_virmanlar', to='kasa.kasa', verbose_name='Hedef Kasa')),
                ('kaynak_kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giden_virmanlar', to='kasa.kasa', verbose_name='Kaynak Kasa')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kasa Virmanı',
                'verbose_name_plural': 'Kasa Virmanları',
                'ordering': ['-tarih'],
            },
        ),
    ]
