# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Marka Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marka_logolari/', verbose_name='Marka Logosu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='UrunKategoriUst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Varyasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('renk', 'Renk'), ('beden', 'Beden'), ('diger', 'Diğer')], max_length=10, verbose_name='Varyasyon Tipi')),
                ('deger', models.CharField(max_length=50, verbose_name='Değer')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Varyasyon',
                'verbose_name_plural': 'Varyasyonlar',
                'ordering': ['tip', 'deger'],
                'unique_together': {('tip', 'deger')},
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barkod', models.CharField(max_length=50, unique=True, verbose_name='Barkod')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Ürün Kodu (SKU)')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('cinsiyet', models.CharField(choices=[('kadin', 'Kadın'), ('erkek', 'Erkek')], default='kadin', max_length=10, verbose_name='Cinsiyet')),
                ('alis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış Fiyatı (KDV Hariç)')),
                ('kar_marji', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Kar Marjı (%)')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('stok_miktari', models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı')),
                ('minimum_stok', models.PositiveIntegerField(default=5, verbose_name='Minimum Stok Uyarı Seviyesi')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urun_resimleri/', verbose_name='Ürün Resmi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('marka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.marka', verbose_name='Marka')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urun.urunkategoriust', verbose_name='Kategori')),
                ('varyasyonlar', models.ManyToManyField(blank=True, to='urun.varyasyon', verbose_name='Varyasyonlar')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
