# Generated by Django 5.2.5 on 2025-09-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varyasyon',
            options={'ordering': ['tip', 'sira', 'deger'], 'verbose_name': 'Varyasyon', 'verbose_name_plural': 'Varyasyonlar'},
        ),
        migrations.RemoveField(
            model_name='urun',
            name='alis_fiyati',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='barkod',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='kar_marji',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='minimum_stok',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='satis_fiyati',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='stok_miktari',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='varyasyonlar',
        ),
        migrations.AddField(
            model_name='urun',
            name='birim',
            field=models.CharField(choices=[('adet', 'Adet'), ('takim', 'Takım'), ('cift', 'Çift'), ('kg', 'Kilogram'), ('gr', 'Gram'), ('lt', 'Litre'), ('ml', 'Mililitre'), ('m', 'Metre'), ('cm', 'Santimetre')], default='adet', max_length=10, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kritik_stok_seviyesi',
            field=models.PositiveIntegerField(default=5, verbose_name='Kritik Stok Seviyesi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='stok_takibi',
            field=models.BooleanField(default=True, verbose_name='Stok Takibi Yapılsın'),
        ),
        migrations.AddField(
            model_name='urun',
            name='temel_alis_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temel Alış Fiyatı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='temel_kar_orani',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Temel Kar Oranı (%)'),
        ),
        migrations.AddField(
            model_name='urun',
            name='temel_satis_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temel Satış Fiyatı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='temel_stok_miktari',
            field=models.PositiveIntegerField(default=0, verbose_name='Temel Stok Miktarı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='varyasyon_tipleri',
            field=models.ManyToManyField(blank=True, limit_choices_to={'aktif': True}, to='urun.varyasyon', verbose_name='Kullanılan Varyasyon Tipleri'),
        ),
        migrations.AddField(
            model_name='urun',
            name='varyasyonlu',
            field=models.BooleanField(default=False, verbose_name='Varyasyonlu Ürün'),
        ),
        migrations.AddField(
            model_name='varyasyon',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='varyasyon',
            name='hex_kodu',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Renk Hex Kodu'),
        ),
        migrations.AddField(
            model_name='varyasyon',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='cinsiyet',
            field=models.CharField(choices=[('kadin', 'Kadın'), ('erkek', 'Erkek'), ('unisex', 'Unisex')], default='kadin', max_length=10, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='urun_resimleri/', verbose_name='Ana Ürün Resmi'),
        ),
        migrations.CreateModel(
            name='UrunVaryanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barkod', models.CharField(max_length=50, unique=True, verbose_name='Barkod')),
                ('alis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış Fiyatı')),
                ('kar_orani', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Kar Oranı (%)')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('stok_miktari', models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı')),
                ('ek_aciklama', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ek Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='varyant_resimleri/', verbose_name='Varyant Resmi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('beden', models.ForeignKey(blank=True, limit_choices_to={'aktif': True, 'tip': 'beden'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beden_varyantlari', to='urun.varyasyon', verbose_name='Beden')),
                ('diger_varyasyon', models.ForeignKey(blank=True, limit_choices_to={'aktif': True, 'tip': 'diger'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diger_varyantlari', to='urun.varyasyon', verbose_name='Diğer Varyasyon')),
                ('renk', models.ForeignKey(blank=True, limit_choices_to={'aktif': True, 'tip': 'renk'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renk_varyantlari', to='urun.varyasyon', verbose_name='Renk')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varyantlari', to='urun.urun', verbose_name='Ana Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Varyantı',
                'verbose_name_plural': 'Ürün Varyantları',
                'ordering': ['urun', 'renk', 'beden', 'diger_varyasyon'],
                'unique_together': {('urun', 'renk', 'beden', 'diger_varyasyon')},
            },
        ),
    ]
