# Generated by Django 5.2.5 on 2025-09-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0002_alter_varyasyon_options_remove_urun_alis_fiyati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, unique=True, verbose_name='Beden Adı')),
                ('kod', models.CharField(max_length=1, unique=True, verbose_name='Beden Kodu (1 karakter)')),
                ('tip', models.CharField(choices=[('harf', 'Harf (XS, S, M, L, XL, XXL)'), ('rakam', 'Rakam (36, 38, 40, 42)')], default='harf', max_length=20, verbose_name='Beden Tipi')),
                ('sira', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beden',
                'verbose_name_plural': 'Bedenler',
                'ordering': ['tip', 'sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Renk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True, verbose_name='Renk Adı')),
                ('kod', models.CharField(max_length=1, unique=True, verbose_name='Renk Kodu (1 harf)')),
                ('hex_kod', models.CharField(blank=True, max_length=7, null=True, verbose_name='Hex Renk Kodu')),
                ('sira', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Renk',
                'verbose_name_plural': 'Renkler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.RemoveField(
            model_name='urun',
            name='varyasyon_tipleri',
        ),
        migrations.AlterModelOptions(
            name='urunkategoriust',
            options={'ordering': ['ad'], 'verbose_name': 'Üst Kategori', 'verbose_name_plural': 'Üst Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='urunvaryanti',
            options={'ordering': ['urun', 'renk', 'beden'], 'verbose_name': 'Ürün Varyantı', 'verbose_name_plural': 'Ürün Varyantları'},
        ),
        migrations.RemoveField(
            model_name='urun',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='temel_alis_fiyati',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='temel_kar_orani',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='temel_satis_fiyati',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='temel_stok_miktari',
        ),
        migrations.AddField(
            model_name='urun',
            name='alis_fiyati',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Alış Fiyatı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kar_orani',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Kar Oranı (%)'),
        ),
        migrations.AddField(
            model_name='urun',
            name='satis_fiyati',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Satış Fiyatı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='urun_kodu',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='Ürün Kodu (5 hane)'),
        ),
        migrations.AddField(
            model_name='urunkategoriust',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='cinsiyet',
            field=models.CharField(choices=[('kadin', 'Kadın'), ('erkek', 'Erkek'), ('unisex', 'Unisex')], default='unisex', max_length=10, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='urunvaryanti',
            name='barkod',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='Barkod'),
        ),
        migrations.AlterField(
            model_name='urunvaryanti',
            name='ek_aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Ek Açıklama'),
        ),
        migrations.AlterField(
            model_name='urunvaryanti',
            name='stok_miktari',
            field=models.PositiveIntegerField(default=1, verbose_name='Stok Miktarı'),
        ),
        migrations.AlterField(
            model_name='urunvaryanti',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varyantlar', to='urun.urun', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='urunvaryanti',
            name='beden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urun.beden', verbose_name='Beden'),
        ),
        migrations.AlterUniqueTogether(
            name='urunvaryanti',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='urunvaryanti',
            name='renk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urun.renk', verbose_name='Renk'),
        ),
        migrations.AlterUniqueTogether(
            name='urunvaryanti',
            unique_together={('urun', 'renk', 'beden')},
        ),
        migrations.RemoveField(
            model_name='urunvaryanti',
            name='alis_fiyati',
        ),
        migrations.RemoveField(
            model_name='urunvaryanti',
            name='diger_varyasyon',
        ),
        migrations.RemoveField(
            model_name='urunvaryanti',
            name='kar_orani',
        ),
        migrations.RemoveField(
            model_name='urunvaryanti',
            name='satis_fiyati',
        ),
        migrations.DeleteModel(
            name='Varyasyon',
        ),
    ]
