# Generated by Django 5.2.5 on 2025-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0003_beden_renk_remove_urun_varyasyon_tipleri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urun_kodu',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Ürün Kodu (5 hane)'),
        ),
    ]
