# Generated by Django 5.2.5 on 2025-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0004_alter_urun_urun_kodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='cinsiyet',
            field=models.CharField(choices=[('kadin', 'Kadın'), ('erkek', 'Erkek')], default='kadin', max_length=10, verbose_name='Cinsiyet'),
        ),
    ]
