# Generated by Django 5.2.5 on 2025-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0005_alter_urun_cinsiyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunvaryanti',
            name='stok_kaydedildi',
            field=models.BooleanField(default=False, verbose_name='Stok Kaydedildi Mi?'),
        ),
    ]
