# Generated by Django 5.2.5 on 2025-09-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0006_urunvaryanti_stok_kaydedildi'),
    ]

    operations = [
    ]
