# Generated by Django 5.2.5 on 2025-09-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0007_auto_20250905_2020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('giris', 'Stok Girişi'), ('cikis', 'Stok Çıkışı'), ('duzeltme', 'Stok Düzeltmesi'), ('sayim', 'Stok Sayımı'), ('transfer', 'Transfer'), ('fire', 'Fire')], max_length=20, verbose_name='Hareket Tipi')),
                ('miktar', models.IntegerField(verbose_name='Miktar')),
                ('onceki_stok', models.IntegerField(verbose_name='Önceki Stok')),
                ('yeni_stok', models.IntegerField(verbose_name='Yeni Stok')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('referans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referans ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('varyant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urun.urunvaryanti', verbose_name='Ürün Varyantı')),
            ],
            options={
                'verbose_name': 'Stok Hareket',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
