# Generated by Django 5.2.5 on 2025-09-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0008_stokhareket'),
    ]

    operations = [
    ]
