# Generated by Django 5.2.5 on 2025-09-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0009_auto_20250906_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokhareket',
            name='hareket_tipi',
            field=models.CharField(choices=[('giris', 'Stok Girişi'), ('cikis', 'Stok Çıkışı'), ('duzeltme', 'Stok Düzeltmesi'), ('sayim_eksik', 'Sayım Eksiği'), ('sayim_fazla', 'Sayım Fazlası'), ('transfer', 'Transfer'), ('fire', 'Fire')], max_length=20, verbose_name='Hareket Tipi'),
        ),
    ]
