# Generated by Django 5.2.5 on 2025-09-13 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0010_alter_stokhareket_hareket_tipi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunvaryanti',
            name='barkod',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Barkod'),
        ),
        migrations.CreateModel(
            name='StokDegisiklikLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('ilk_kayit', 'İlk Kayıt'), ('admin_degisiklik', 'Admin Değişiklik'), ('sistem_degisiklik', 'Sistem Değişiklik'), ('sistem_kilitleme', 'Sistem Kilitleme (Yeni Varyasyon)'), ('stok_hareket', 'Stok Hareket'), ('koruma_kaldirma', 'Koruma Kaldırma')], max_length=20, verbose_name='İşlem Tipi')),
                ('eski_miktar', models.PositiveIntegerField(verbose_name='Eski Miktar')),
                ('yeni_miktar', models.PositiveIntegerField(verbose_name='Yeni Miktar')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('varyant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_loglari', to='urun.urunvaryanti')),
            ],
            options={
                'verbose_name': 'Stok Değişiklik Logu',
                'verbose_name_plural': 'Stok Değişiklik Logları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
