# Generated by Django 5.2.5 on 2025-10-11 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0011_alter_urunvaryanti_barkod_stokdegisikliklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='urun',
            index=models.Index(fields=['aktif', 'kategori'], name='urun_urun_aktif_2399e5_idx'),
        ),
        migrations.AddIndex(
            model_name='urun',
            index=models.Index(fields=['marka', 'aktif'], name='urun_urun_marka_i_e3e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='urun',
            index=models.Index(fields=['cinsiyet', 'aktif'], name='urun_urun_cinsiye_01edca_idx'),
        ),
        migrations.AddIndex(
            model_name='urun',
            index=models.Index(fields=['urun_kodu'], name='urun_urun_urun_ko_8b619e_idx'),
        ),
        migrations.AddIndex(
            model_name='urun',
            index=models.Index(fields=['ad'], name='urun_urun_ad_ee86d9_idx'),
        ),
        migrations.AddIndex(
            model_name='urun',
            index=models.Index(fields=['-olusturma_tarihi'], name='urun_urun_olustur_4713da_idx'),
        ),
        migrations.AddIndex(
            model_name='urunvaryanti',
            index=models.Index(fields=['urun', 'aktif'], name='urun_urunva_urun_id_19ff63_idx'),
        ),
        migrations.AddIndex(
            model_name='urunvaryanti',
            index=models.Index(fields=['stok_miktari'], name='urun_urunva_stok_mi_928cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='urunvaryanti',
            index=models.Index(fields=['barkod'], name='urun_urunva_barkod_35595f_idx'),
        ),
        migrations.AddIndex(
            model_name='urunvaryanti',
            index=models.Index(fields=['urun', 'renk', 'beden'], name='urun_urunva_urun_id_db1679_idx'),
        ),
    ]
