# Generated by Django 5.2.5 on 2025-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0012_urun_urun_urun_aktif_2399e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='pesin_fiyat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peşin ödeme fiyatı', max_digits=10, verbose_name='Peşin Fiyat'),
        ),
        migrations.AddField(
            model_name='urun',
            name='taksit_orani',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Peşin fiyata eklenecek yüzde', max_digits=5, verbose_name='Taksit Fark Oranı (%)'),
        ),
        migrations.AddField(
            model_name='urun',
            name='taksitli_fiyat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Otomatik hesaplanır (Peşin + %5)', max_digits=10, verbose_name='Taksitli Fiyat'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='satis_fiyati',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Artık pesin_fiyat kullanılıyor', max_digits=10, verbose_name='Satış Fiyatı (ESKİ - Kullanılmıyor)'),
        ),
    ]
