# Generated by Django 5.2.5 on 2025-11-16 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0013_urun_pesin_fiyat_urun_taksit_orani_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_alis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Eski Alış Fiyatı')),
                ('yeni_alis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yeni Alış Fiyatı')),
                ('eski_satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Eski Satış Fiyatı')),
                ('yeni_satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yeni Satış Fiyatı')),
                ('degisiklik_yuzdesi', models.DecimalField(decimal_places=2, help_text='Satış fiyatındaki değişim yüzdesi', max_digits=7, verbose_name='Değişim Yüzdesi (%)')),
                ('degisiklik_miktari', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Değişim Miktarı (TL)')),
                ('neden', models.CharField(choices=[('zam', 'Fiyat Zammı'), ('indirim', 'İndirim'), ('kampanya', 'Kampanya'), ('sezon_sonu', 'Sezon Sonu İndirimi'), ('maliyet', 'Maliyet Artışı'), ('duzeltme', 'Fiyat Düzeltme'), ('toplu_guncelleme', 'Toplu Güncelleme'), ('enflasyon', 'Enflasyon Zammı'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Değişiklik Nedeni')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('degisiklik_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Değişiklik Tarihi')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('gecerlilik_baslangic', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Başlangıç')),
                ('gecerlilik_bitis', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitiş')),
                ('otomatik_geri_al', models.BooleanField(default=False, help_text='Kampanya bitiminde eski fiyata geri dön', verbose_name='Otomatik Geri Al')),
                ('geri_alindi', models.BooleanField(default=False, verbose_name='Geri Alındı')),
                ('degistiren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Değiştiren Kullanıcı')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyat_gecmisi', to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Fiyat Geçmişi',
                'verbose_name_plural': 'Fiyat Geçmişleri',
                'ordering': ['-degisiklik_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='FiyatKampanya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Kampanya Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kampanya_turu', models.CharField(choices=[('indirim_yuzde', 'Yüzde İndirim'), ('indirim_tutar', 'Tutar İndirim'), ('zam_yuzde', 'Yüzde Zam'), ('sabit_fiyat', 'Sabit Fiyat')], default='indirim_yuzde', max_length=20, verbose_name='Kampanya Türü')),
                ('deger', models.DecimalField(decimal_places=2, help_text='İndirim/Zam yüzdesi veya tutarı', max_digits=10, verbose_name='Değer')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('cinsiyet', models.CharField(blank=True, choices=[('kadin', 'Kadın'), ('erkek', 'Erkek')], max_length=10, null=True, verbose_name='Cinsiyet Filtresi')),
                ('min_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Fiyat')),
                ('max_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum Fiyat')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('beklemede', 'Beklemede'), ('aktif', 'Aktif'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='taslak', max_length=20, verbose_name='Durum')),
                ('otomatik_geri_al', models.BooleanField(default=True, help_text='Kampanya bitiminde eski fiyatlara dön', verbose_name='Otomatik Geri Al')),
                ('geri_alindi', models.BooleanField(default=False, verbose_name='Geri Alındı')),
                ('etkilenen_urun_sayisi', models.PositiveIntegerField(default=0, verbose_name='Etkilenen Ürün Sayısı')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kategoriler', models.ManyToManyField(blank=True, to='urun.urunkategoriust', verbose_name='Kategoriler')),
                ('markalar', models.ManyToManyField(blank=True, to='urun.marka', verbose_name='Markalar')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('urunler', models.ManyToManyField(blank=True, to='urun.urun', verbose_name='Belirli Ürünler')),
            ],
            options={
                'verbose_name': 'Fiyat Kampanyası',
                'verbose_name_plural': 'Fiyat Kampanyaları',
                'ordering': ['-baslangic_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='FiyatUyari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyari_turu', models.CharField(choices=[('buyuk_artis', 'Büyük Fiyat Artışı'), ('buyuk_dusus', 'Büyük Fiyat Düşüşü'), ('minimum_altinda', 'Minimum Fiyatın Altında'), ('maksimum_ustunde', 'Maksimum Fiyatın Üstünde'), ('kar_marji_dusuk', 'Kar Marjı Çok Düşük')], max_length=20, verbose_name='Uyarı Türü')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('fiyat_gecmisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.fiyatgecmisi', verbose_name='İlgili Fiyat Değişikliği')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyat_uyarilari', to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Fiyat Uyarısı',
                'verbose_name_plural': 'Fiyat Uyarıları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.AddIndex(
            model_name='fiyatgecmisi',
            index=models.Index(fields=['urun', '-degisiklik_tarihi'], name='urun_fiyatg_urun_id_a3f57e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiyatgecmisi',
            index=models.Index(fields=['degistiren', '-degisiklik_tarihi'], name='urun_fiyatg_degisti_005720_idx'),
        ),
        migrations.AddIndex(
            model_name='fiyatgecmisi',
            index=models.Index(fields=['neden'], name='urun_fiyatg_neden_dc0a14_idx'),
        ),
        migrations.AddIndex(
            model_name='fiyatgecmisi',
            index=models.Index(fields=['gecerlilik_bitis'], name='urun_fiyatg_gecerli_ee0870_idx'),
        ),
    ]
