# Generated by Django 5.2.5 on 2026-04-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0014_fiyatgecmisi_fiyatkampanya_fiyatuyari_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiketSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Şablon için bir isim giriniz', max_length=100, verbose_name='Şablon Adı')),
                ('genislik_mm', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Genişlik (mm)')),
                ('yukseklik_mm', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Yükseklik (mm)')),
                ('tasarim_json', models.JSONField(default=dict, help_text='Canvas durumu JSON formatında', verbose_name='Tasarım Verisi')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan Şablon')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiket_sablonlari', to='urun.urunkategoriust', verbose_name='Kategori')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_sablonlar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Etiket Şablonu',
                'verbose_name_plural': 'Etiket Şablonları',
                'db_table': 'urun_etiket_sablonu',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='EtiketSablonEleman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleman_tipi', models.CharField(choices=[('text', 'Metin'), ('barcode_1d', '1D Barkod'), ('barcode_2d', '2D Barkod (QR)'), ('image', 'Resim/Logo'), ('rectangle', 'Dikdörtgen'), ('line', 'Çizgi')], max_length=20, verbose_name='Element Tipi')),
                ('pozisyon_x', models.IntegerField(default=0, verbose_name='X Pozisyonu')),
                ('pozisyon_y', models.IntegerField(default=0, verbose_name='Y Pozisyonu')),
                ('genislik', models.IntegerField(default=50, verbose_name='Genişlik')),
                ('yukseklik', models.IntegerField(default=20, verbose_name='Yükseklik')),
                ('donderece', models.IntegerField(default=0, verbose_name='Döndürme Açısı')),
                ('icerik', models.TextField(blank=True, verbose_name='İçerik')),
                ('veri_alan', models.CharField(blank=True, help_text='Örn: {urun_ad}, {barkod}, {fiyat}', max_length=50, verbose_name='Veri Alanı')),
                ('font_aile', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New')], default='Arial', max_length=50, verbose_name='Font Ailesi')),
                ('font_boyut', models.IntegerField(default=12, verbose_name='Font Boyutu (pt)')),
                ('font_kalin', models.BooleanField(default=False, verbose_name='Kalın')),
                ('font_renk', models.CharField(default='#000000', max_length=7, verbose_name='Font Rengi')),
                ('arka_plan_renk', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Arka Plan Rengi')),
                ('barkod_tipi', models.CharField(blank=True, choices=[('CODE128', 'Code 128'), ('CODE39', 'Code 39'), ('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPCA', 'UPC-A'), ('UPCE', 'UPC-E')], max_length=20, verbose_name='Barkod Tipi')),
                ('barkod_yukseklik', models.IntegerField(default=20, verbose_name='Barkod Yüksekliği (mm)')),
                ('insan_okunabilir', models.BooleanField(default=True, verbose_name='İnsan Okunabilir Metin')),
                ('kenarlik_kalinligi', models.IntegerField(default=1, verbose_name='Kenarlık Kalınlığı')),
                ('kenarlik_rengi', models.CharField(default='#000000', max_length=7, verbose_name='Kenarlık Rengi')),
                ('dolgu_rengi', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Dolgu Rengi')),
                ('kose_yuvarlakligi', models.IntegerField(default=0, verbose_name='Köşe Yuvarlaklığı')),
                ('gorunum_url', models.CharField(blank=True, max_length=500, verbose_name='Görsel URL')),
                ('siralama', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('sablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemanlar', to='urun.etiketsablonu', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Şablon Elemanı',
                'verbose_name_plural': 'Şablon Elemanları',
                'db_table': 'urun_etiket_sablon_eleman',
                'ordering': ['siralama'],
            },
        ),
        migrations.CreateModel(
            name='YaziciAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazici_ad', models.CharField(default='Xprinter XP-470B', max_length=100, verbose_name='Yazıcı Adı')),
                ('yazici_tipi', models.CharField(default='Xprinter XP-470B', max_length=50, verbose_name='Yazıcı Tipi')),
                ('etiket_genislik_mm', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Etiket Genişliği (mm)')),
                ('etiket_yukseklik_mm', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Etiket Yüksekliği (mm)')),
                ('kopya_sayisi', models.IntegerField(default=1, verbose_name='Kopya Sayısı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('print_agent_token', models.CharField(blank=True, max_length=100, verbose_name='Print Agent Token')),
                ('son_test_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son Test Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yazici_ayarlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yazıcı Ayarları',
                'verbose_name_plural': 'Yazıcı Ayarları',
                'db_table': 'urun_yazici_ayarlari',
            },
        ),
    ]
