# Generated by Django 5.2.5 on 2026-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0015_etiketsablonu_etiketsabloneleman_yaziciayarlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiketsablonu',
            name='genislik_mm',
            field=models.DecimalField(decimal_places=2, default=54, help_text='Nuvia ZPL şablonu: 54×40 mm (^PW432 ^LL320, 8 dot/mm)', max_digits=5, verbose_name='Genişlik (mm)'),
        ),
        migrations.AlterField(
            model_name='etiketsablonu',
            name='yukseklik_mm',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Nuvia ZPL şablonu: 54×40 mm', max_digits=5, verbose_name='Yükseklik (mm)'),
        ),
    ]
