"""
Nuvia Premium Wear — etiket tasarımcısı öğeleri (ZPL ^FT/^FO konumları / 8 = mm).
Yazdırılan çıktı: stoktakip.tsc_to_zpl_converter.build_nuvia_exact_zpl (birebir aynı düzen).
"""

# ZPL çizim sırasıyla uyumlu: metinler → kutu çerçevesi → Code 128 barkod
NUVIA_PREMIUM_ELEMENTS = [
    {'id': 1, 'type': 'text', 'x': 16.875, 'y': 8.875, 'width': 22.0, 'height': 9.0,
     'content': 'NUVIA', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 33,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': True, 'rotation': 0},
    {'id': 2, 'type': 'text', 'x': 2.375, 'y': 12.25, 'width': 50.0, 'height': 4.5,
     'content': 'PREMIUM WEAR MAN & WOMAN', 'dataField': '', 'fontFamily': 'Arial',
     'fontSize': 14, 'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 3, 'type': 'text', 'x': 3.75, 'y': 23.125, 'width': 12.0, 'height': 3.2,
     'content': 'Beden', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 4, 'type': 'text', 'x': 12.75, 'y': 23.125, 'width': 14.0, 'height': 3.5,
     'content': 'XXL', 'dataField': '{beden}', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 5, 'type': 'text', 'x': 30.25, 'y': 18.125, 'width': 10.0, 'height': 3.0,
     'content': 'Pesin', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 6, 'type': 'text', 'x': 40.5, 'y': 18.125, 'width': 12.0, 'height': 3.2,
     'content': '1200', 'dataField': '{pesin_fiyat}', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 7, 'type': 'text', 'x': 48.25, 'y': 18.125, 'width': 6.0, 'height': 3.0,
     'content': 'TL', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 8, 'type': 'text', 'x': 3.75, 'y': 18.125, 'width': 8.0, 'height': 3.0,
     'content': 'Kod', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 9, 'type': 'text', 'x': 12.125, 'y': 18.125, 'width': 14.0, 'height': 3.2,
     'content': '0001', 'dataField': '{urun_kodu}', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 10, 'type': 'text', 'x': 30.25, 'y': 23.125, 'width': 14.0, 'height': 3.2,
     'content': 'Taksitli', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 11, 'type': 'text', 'x': 40.5, 'y': 23.125, 'width': 12.0, 'height': 3.2,
     'content': '1400', 'dataField': '{taksitli_fiyat}', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 12, 'type': 'text', 'x': 48.25, 'y': 23.125, 'width': 6.0, 'height': 3.2,
     'content': 'TL', 'dataField': '', 'fontFamily': 'Arial', 'fontSize': 12,
     'fontColor': '#000000', 'bgColor': 'transparent', 'bold': False, 'rotation': 0},
    {'id': 13, 'type': 'rectangle', 'x': 2.625, 'y': 13.0, 'width': 49.25, 'height': 12.25,
     'borderMm': 3, 'bgColor': 'transparent', 'rotation': 0},
    {'id': 14, 'type': 'barcode_1d', 'x': 0.875, 'y': 36.125, 'width': 42.0, 'height': 9.5,
     'content': '', 'dataField': '{barkod}', 'barcodeType': 'CODE128', 'barcodeHeight': 38,
     'rotation': 0},
]
