# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tutar')),
                ('odeme_yontemi', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kredi/Banka Kartı'), ('havale', 'Havale/EFT'), ('cek', 'Çek'), ('diger', 'Diğer')], default='nakit', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('tarih', models.DateField(verbose_name='Gider Tarihi')),
                ('fatura_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatura/Fiş No')),
                ('tedarikci', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tedarikçi/Firma')),
                ('fatura_fotografi', models.ImageField(blank=True, null=True, upload_to='giderler/faturalar/', verbose_name='Fatura/Fiş Fotoğrafı')),
                ('ek_belge', models.FileField(blank=True, null=True, upload_to='giderler/belgeler/', verbose_name='Ek Belge')),
                ('tekrarlayan', models.BooleanField(default=False, verbose_name='Tekrarlayan Gider')),
                ('tekrar_periyodu', models.CharField(blank=True, choices=[('gunluk', 'Günlük'), ('haftalik', 'Haftalık'), ('aylik', 'Aylık'), ('yillik', 'Yıllık')], max_length=20, null=True, verbose_name='Tekrar Periyodu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-tarih', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='GiderKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('renk', models.CharField(default='#6c757d', help_text='Hex renk kodu (örn: #FF5733)', max_length=7, verbose_name='Renk Kodu')),
                ('ikon', models.CharField(default='fas fa-money-bill', help_text='FontAwesome ikon sınıfı', max_length=50, verbose_name='İkon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
                'ordering': ['ad'],
            },
        ),
    ]
