# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gider',
            name='olusturan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='gider',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gider.giderkategori', verbose_name='Kategori'),
        ),
        migrations.AddIndex(
            model_name='gider',
            index=models.Index(fields=['tarih'], name='gider_gider_tarih_7d515a_idx'),
        ),
        migrations.AddIndex(
            model_name='gider',
            index=models.Index(fields=['kategori'], name='gider_gider_kategor_28f96b_idx'),
        ),
        migrations.AddIndex(
            model_name='gider',
            index=models.Index(fields=['olusturan'], name='gider_gider_olustur_2bd992_idx'),
        ),
    ]
