# Generated by Django 5.2.5 on 2025-09-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_permissions',
            field=models.TextField(blank=True, help_text='Virgül ile ayrılmış yetki kodları', verbose_name='Özel Yetkiler'),
        ),
    ]
