# Generated by Django 5.2.5 on 2025-09-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0002_userprofile_custom_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(choices=[('dashboard', 'Ana Sayfa'), ('urun_liste', 'Ürün Listesi'), ('urun_ekle', 'Ürün Ekle'), ('urun_kategori', 'Kategori Yönetimi'), ('urun_marka', 'Marka Yönetimi'), ('urun_stok', 'Stok Durumu'), ('urun_en_cok_satan', 'En Çok Satanlar'), ('urun_kar_zarar', 'Kar Zarar Raporu'), ('urun_barkod', 'Barkod Sorgula'), ('satis_ekrani', 'Satış Ekranı'), ('satis_liste', 'Satış Listesi'), ('satis_tahsilat_liste', 'Tahsilat Listesi'), ('satis_tahsilat_rapor', 'Tahsilat Raporları'), ('satis_iade', 'Satış İade'), ('hediye_cekleri', 'Hediye Çekleri'), ('musteri_liste', 'Müşteri Listesi'), ('musteri_ekle', 'Müşteri Ekle'), ('musteri_borc_alacak', 'Borç-Alacak Takip'), ('musteri_tahsilat', 'Tahsilat İşlemleri'), ('gider_liste', 'Gider Listesi'), ('gider_ekle', 'Gider Ekle'), ('gider_rapor', 'Gider Raporları'), ('gider_kategori', 'Gider Kategorileri'), ('rapor_gunluk', 'Günlük Rapor'), ('rapor_stok', 'Stok Raporu'), ('rapor_en_cok_satan', 'En Çok Satanlar Raporu'), ('rapor_kar_zarar', 'Kar/Zarar Raporu'), ('rapor_tahsilat', 'Tahsilat Raporu'), ('kullanici_liste', 'Kullanıcı Listesi'), ('kullanici_ekle', 'Kullanıcı Ekle'), ('kullanici_oturum', 'Aktif Oturumlar'), ('kullanici_aktivite', 'Kullanıcı Aktiviteleri'), ('sistem_log', 'Sistem Logları')], max_length=50, unique=True, verbose_name='Menü Anahtarı')),
                ('name', models.CharField(max_length=100, verbose_name='Menü Adı')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('url_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL Adı')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_admin_only', models.BooleanField(default=False, verbose_name='Sadece Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Menü Yetkisi',
                'verbose_name_plural': 'Menü Yetkileri',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_permissions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_menus',
            field=models.ManyToManyField(blank=True, help_text='Kullanıcının erişebileceği menüler', to='kullanici.menupermission', verbose_name='İzin Verilen Menüler'),
        ),
    ]
