# Generated by Django 5.2.5 on 2025-09-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0003_menupermission_remove_userprofile_custom_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi'), ('MANAGER', 'Mağaza Müdürü'), ('SALES', 'Satış Sorumlusu'), ('WAREHOUSE', 'Depo Sorumlusu'), ('VIEWER', 'Görüntüleme Yetkisi')], default='VIEWER', max_length=20, verbose_name='Rol'),
        ),
    ]
