# Generated by Django 5.2.5 on 2025-09-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0004_alter_customuser_role'),
    ]

    operations = [
    ]
