# Generated by Django 5.2.5 on 2025-09-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0005_auto_20250904_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_menus',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Sistem Yöneticisi'), ('manager', 'Mağaza Müdürü'), ('cashier', 'Kasiyer'), ('stock_clerk', 'Depo Sorumlusu'), ('viewer', 'Görüntüleme Yetkisi')], default='viewer', max_length=20, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='MenuPermission',
        ),
    ]
