# Generated by Django 5.2.5 on 2025-10-25 15:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0006_remove_userprofile_allowed_menus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaticiProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Satış Elemanı',
                'verbose_name_plural': 'Satış Elemanları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kullanici.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
