# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AktiviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivite_tipi', models.CharField(choices=[('ekleme', 'Ekleme'), ('guncelleme', 'Güncelleme'), ('silme', 'Silme'), ('satis', 'Satış'), ('stok_guncelleme', 'Stok Güncelleme'), ('giris', 'Kullanıcı Girişi'), ('cikis', 'Kullanıcı Çıkışı'), ('rapor', 'Rapor Oluşturma'), ('iade', 'İade İşlemi'), ('iptal', 'İptal İşlemi')], max_length=20, verbose_name='Aktivite Tipi')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('tarayici_bilgisi', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('eski_degerler', models.JSONField(blank=True, null=True, verbose_name='Eski Değerler')),
                ('yeni_degerler', models.JSONField(blank=True, null=True, verbose_name='Yeni Değerler')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Aktivite Log',
                'verbose_name_plural': 'Aktivite Logları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giris_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Giriş Tarihi')),
                ('cikis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Tarihi')),
                ('ip_adresi', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('tarayici_bilgisi', models.TextField(verbose_name='Tarayıcı Bilgisi')),
                ('basarili', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('hata_mesaji', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Giriş Log',
                'verbose_name_plural': 'Giriş Logları',
                'ordering': ['-giris_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SistemHatasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(choices=[('bilgi', 'Bilgi'), ('uyari', 'Uyarı'), ('hata', 'Hata'), ('kritik', 'Kritik')], max_length=10, verbose_name='Hata Seviyesi')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('mesaj', models.TextField(verbose_name='Hata Mesajı')),
                ('dosya_yolu', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dosya Yolu')),
                ('satir_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satır No')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Stack Trace')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('http_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP Method')),
                ('cozuldu', models.BooleanField(default=False, verbose_name='Çözüldü')),
                ('cozum_notu', models.TextField(blank=True, null=True, verbose_name='Çözüm Notu')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sistem Hatası',
                'verbose_name_plural': 'Sistem Hataları',
                'ordering': ['-tarih'],
            },
        ),
    ]
