# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HediyeCeki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Hediye Çeki Kodu')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Çek Tutarı')),
                ('kalan_tutar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kalan Tutar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('gecerlilik_tarihi', models.DateField(verbose_name='Geçerlilik Tarihi')),
                ('kullanilma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Kullanılma Tarihi')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('kullanilmis', 'Kullanılmış'), ('iptal', 'İptal'), ('suresi_dolmus', 'Süresi Dolmuş')], default='aktif', max_length=20, verbose_name='Durum')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Hediye Çeki',
                'verbose_name_plural': 'Hediye Çekleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='HediyeCekiKullanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanilan_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kullanılan Tutar')),
                ('kullanim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kullanım Tarihi')),
                ('satis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satış ID')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Hediye Çeki Kullanımı',
                'verbose_name_plural': 'Hediye Çeki Kullanımları',
                'ordering': ['-kullanim_tarihi'],
            },
        ),
    ]
