# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hediye', '0001_initial'),
        ('musteri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hediyeceki',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musteri.musteri', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='hediyeceki',
            name='olusturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_hediye_cekleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='hediyecekikullanim',
            name='hediye_ceki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanimlar', to='hediye.hediyeceki', verbose_name='Hediye Çeki'),
        ),
        migrations.AddField(
            model_name='hediyecekikullanim',
            name='kullanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanan'),
        ),
    ]
