# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriGruplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Grup Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('indirim_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İndirim Oranı (%)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri Grup',
                'verbose_name_plural': 'Müşteri Grupları',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('telefon', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('il', models.CharField(blank=True, max_length=50, null=True, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe')),
                ('posta_kodu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('tip', models.CharField(choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=20, verbose_name='Müşteri Tipi')),
                ('firma_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma Adı')),
                ('vergi_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi No')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi')),
                ('tc_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('acik_hesap_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Açık Hesap Bakiyesi')),
                ('acik_hesap_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Açık Hesap Limiti')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.CreateModel(
            name='Tahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tahsilat Tutarı')),
                ('tahsilat_tipi', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kart'), ('havale', 'Havale/EFT'), ('cek', 'Çek'), ('senet', 'Senet')], max_length=20, verbose_name='Tahsilat Tipi')),
                ('tahsilat_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tahsilat Tarihi')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('cek_senet_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Çek/Senet No')),
                ('banka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banka')),
                ('referans_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referans No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('tahsilat_no', models.CharField(max_length=20, unique=True, verbose_name='Tahsilat No')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('durum', models.CharField(choices=[('tahsil_edildi', 'Tahsil Edildi'), ('beklemede', 'Beklemede'), ('iptal', 'İptal'), ('iade', 'İade')], default='tahsil_edildi', max_length=20, verbose_name='Durum')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri', verbose_name='Müşteri')),
                ('tahsilat_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tahsilat Eden')),
            ],
            options={
                'verbose_name': 'Tahsilat',
                'verbose_name_plural': 'Tahsilatlar',
                'ordering': ['-tahsilat_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='BorcAlacakHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('borc', 'Borç'), ('alacak', 'Alacak'), ('duzeltme', 'Düzeltme')], max_length=20, verbose_name='Hareket Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('satis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satış ID')),
                ('onceki_bakiye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Önceki Bakiye')),
                ('yeni_bakiye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yeni Bakiye')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('hareket_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Hareket Tarihi')),
                ('islem_yapan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri', verbose_name='Müşteri')),
                ('tahsilat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musteri.tahsilat', verbose_name='Tahsilat')),
            ],
            options={
                'verbose_name': 'Borç Alacak Hareket',
                'verbose_name_plural': 'Borç Alacak Hareketleri',
                'ordering': ['-hareket_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='TahsilatDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_id', models.PositiveIntegerField(verbose_name='Satış ID')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Tutar')),
                ('tahsilat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='musteri.tahsilat', verbose_name='Tahsilat')),
            ],
            options={
                'verbose_name': 'Tahsilat Detay',
                'verbose_name_plural': 'Tahsilat Detayları',
            },
        ),
        migrations.CreateModel(
            name='MusteriGrupUyelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslama_tarihi', models.DateField(verbose_name='Başlama Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musterigruplar', verbose_name='Grup')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Grup Üyelik',
                'verbose_name_plural': 'Müşteri Grup Üyelikleri',
                'unique_together': {('musteri', 'grup')},
            },
        ),
    ]
