# Generated by Django 5.2.5 on 2025-09-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahsilat',
            name='taksit_sayisi',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Taksit Sayısı'),
        ),
    ]
