# Generated by Django 5.2.5 on 2026-02-09 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0002_tahsilat_taksit_sayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borcalacakhareket',
            name='hareket_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hareket Tarihi'),
        ),
    ]
