"""
Django settings for stoktakip project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-_l8=*rmi(*guvey5ndw6rqux34#=r9s4^=qaa-xh7s=-y6@x01')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'nuviabutik.com',
    'www.nuviabutik.com',
    '31.57.33.34',
    'testserver',  # For Django testing
    # Your production domain will be added here
]

# Add any additional hosts from environment
additional_hosts = os.environ.get('ADDITIONAL_HOSTS', '')
if additional_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in additional_hosts.split(',')])

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://nuviabutik.com',
    'http://nuviabutik.com',
    'https://31.57.33.34',
    'http://31.57.33.34',
    # Your production HTTPS domains will be added here
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'stoktakip.apps.StoktakipConfig',  # Auto-reload optimizasyonları için
    'kullanici',  # Kullanıcı yönetim sistemi
    'urun',
    'satis',
    'musteri',
    'hediye',
    'rapor',
    'log',
    'gider',  # Giderler modülü
    'kasa',   # Kasa yönetimi modülü
    # 'downloads' app kaldırıldı - Local Print Agent kullanılıyor
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files serving for production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # # 'django.middleware.csrf.CsrfViewMiddleware',  # GEÇİCİ KAPALI  # GEÇİCİ OLARAK KAPALI
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Messages middleware önce olmalı
    # 'kullanici.middleware.admin_access.AdminAccessMiddleware',  # GEÇİCİ KAPALI  # Admin panel erişim kontrolü
    # 'kullanici.middleware.user_session.UserSessionMiddleware',  # GEÇİCİ KAPALI  # Oturum kontrolü
    # 'kullanici.middleware.permission_check.PermissionCheckMiddleware',  # GEÇİCİ KAPALI  # Yetki kontrolü
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stoktakip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stoktakip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nuviabutik_db',
        'USER': 'nuviabutik_user',
        'PASSWORD': 'nuviabutik123',
        'HOST': 'localhost',
        'PORT': '5432',
        'CONN_MAX_AGE': 600,  # Persistent connections (10 dakika)
        'CONN_HEALTH_CHECKS': True,  # Bağlantı sağlık kontrolü
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000'  # 30 saniye query timeout
        },
    }
}

# Production database configuration via environment variables
if 'DATABASE_URL' in os.environ:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for production static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = '/kullanici/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/kullanici/login/'

# Custom User Model
AUTH_USER_MODEL = 'kullanici.CustomUser'

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Development optimizations for auto-reload
if DEBUG:
    # Auto-reload optimizations
    USE_TZ = True
    
    # File system polling interval (saniye)
    # Dosya değişikliklerini daha hızlı algılar
    import os
    os.environ.setdefault('DJANGO_AUTORELOAD_EXTRA_FILES', '')
    
    # Cache ayarları - performans için geliştirme
    # Redis Cache Configuration (Yüksek Performans)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'nuviabutik',
            'TIMEOUT': 300,  # 5 dakika default timeout
        }
    }
    
    # Session cache (Redis)
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
    
    # Template cache'i etkinleştir - production performansı için
    for template_settings in TEMPLATES:
        if 'OPTIONS' in template_settings:
            template_settings['OPTIONS']['debug'] = False


# CSRF Security Settings
CSRF_COOKIE_SECURE = False  # GEÇİCİ
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

# Session Security Settings
SESSION_COOKIE_SECURE = not DEBUG  # Production'da HTTPS üzerinden gönder
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 3600  # 1 saat

# Security Headers (Production için)
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# GEÇİCİ CSRF AYARLARI
