# Generated by Django 5.2.5 on 2025-09-03 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri', '0001_initial'),
        ('urun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Sipariş No')),
                ('satis_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Satış No')),
                ('ara_toplam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ara Toplam')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KDV Tutarı')),
                ('genel_toplam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Genel Toplam')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('tamamlandi', 'Tamamlandı'), ('iade', 'İade'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('siparis_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('satis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Satış Tarihi')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musteri.musteri', verbose_name='Müşteri')),
                ('satici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_tipi', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kart'), ('hediye_ceki', 'Hediye Çeki'), ('acik_hesap', 'Açık Hesap')], max_length=20, verbose_name='Ödeme Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('taksit_sayisi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taksit Sayısı')),
                ('taksit_tutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taksit Tutarı')),
                ('hediye_ceki_kodu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hediye Çeki Kodu')),
                ('para_ustu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Para Üstü')),
                ('odeme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satis.satis', verbose_name='Satış')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-odeme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat')),
                ('indirim_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İndirim Oranı (%)')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satis.satis', verbose_name='Satış')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış Detay',
                'verbose_name_plural': 'Satış Detayları',
            },
        ),
        migrations.CreateModel(
            name='SatisIptal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iptal_nedeni', models.TextField(verbose_name='İptal Nedeni')),
                ('iptal_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İptal Tarihi')),
                ('stok_iade_edildi', models.BooleanField(default=False, verbose_name='Stok İade Edildi')),
                ('iptal_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İptal Eden')),
                ('satis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='satis.satis', verbose_name='İptal Edilen Satış')),
            ],
            options={
                'verbose_name': 'Satış İptal',
                'verbose_name_plural': 'Satış İptalleri',
                'ordering': ['-iptal_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiparisNumarasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveIntegerField(verbose_name='Yıl')),
                ('ay', models.PositiveIntegerField(verbose_name='Ay')),
                ('gun', models.PositiveIntegerField(verbose_name='Gün')),
                ('sayac', models.PositiveIntegerField(default=0, verbose_name='Günlük Sayaç')),
            ],
            options={
                'verbose_name': 'Sipariş Numarası',
                'verbose_name_plural': 'Sipariş Numaraları',
                'unique_together': {('yil', 'ay', 'gun')},
            },
        ),
    ]
