# Generated by Django 5.2.5 on 2025-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='odeme_tipi',
            field=models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kredi Kartı'), ('havale', 'Havale'), ('hediye_ceki', 'Hediye Çeki'), ('acik_hesap', 'Açık Hesap')], max_length=20, verbose_name='Ödeme Tipi'),
        ),
    ]
