# Generated by Django 5.2.5 on 2025-09-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0002_alter_odeme_odeme_tipi'),
        ('urun', '0004_alter_urun_urun_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisdetay',
            name='varyant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urun.urunvaryanti', verbose_name='Varyant'),
        ),
    ]
