# Generated by Django 5.2.5 on 2025-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0003_satisdetay_varyant'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama/Not'),
        ),
    ]
