# Generated by Django 5.2.5 on 2025-09-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0004_odeme_aciklama'),
    ]

    operations = [
    ]
