# Generated by Django 5.2.5 on 2025-10-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0005_auto_20250906_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='banka',
            field=models.CharField(blank=True, choices=[('isbank', 'İŞBANKASI'), ('ziraat', 'ZİRAAT BANKASI'), ('yapikredi', 'YAPIKREDİ BANKASI'), ('akbank', 'AKBANK')], max_length=20, null=True, verbose_name='Banka'),
        ),
    ]
