# Generated by Django 5.2.5 on 2025-10-11 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0002_tahsilat_taksit_sayisi'),
        ('satis', '0006_odeme_banka'),
        ('urun', '0012_urun_urun_urun_aktif_2399e5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisSiparisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(max_length=20, unique=True, verbose_name='Sipariş No')),
                ('ara_toplam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ara Toplam')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KDV Tutarı')),
                ('genel_toplam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Genel Toplam')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('hazir', 'Satışa Hazır'), ('satisa_donusturuldu', 'Satışa Dönüştürüldü'), ('iptal', 'İptal')], default='taslak', max_length=20, verbose_name='Durum')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('odeme_yontemi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ödeme Yöntemi')),
                ('odeme_detaylari', models.JSONField(blank=True, null=True, verbose_name='Ödeme Detayları')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musteri.musteri', verbose_name='Müşteri')),
                ('satici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
                ('satis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satis.satis', verbose_name='Bağlı Satış')),
            ],
            options={
                'verbose_name': 'Satış Siparişi',
                'verbose_name_plural': 'Satış Siparişleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisSiparisiDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('indirim_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İndirim Oranı (%)')),
                ('indirim_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('toplam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satis.satissiparisi', verbose_name='Sipariş')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış Siparişi Detayı',
                'verbose_name_plural': 'Satış Siparişi Detayları',
            },
        ),
    ]
