# Generated by Django 5.2.5 on 2025-10-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satis', '0007_satissiparisi_satissiparisidetay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satissiparisidetay',
            name='siparis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='satis.satissiparisi', verbose_name='Sipariş'),
        ),
    ]
